version-template: 'v$MAJOR.$MINOR'
name-template: 'v$NEXT_MINOR_VERSION Release.'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES