name: "Skyduino Roaster PCB"

permissions:
  contents: write

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      fabrication:
        description: Fabrication Outputs
        required: false
        default: true
        type: boolean

      bom:
        description: Bill of materials
        required: false
        default: true
        type: boolean

      models:
        description: 3D renderings, Step files
        required: false
        default: true
        type: boolean

      docs:
        description: PCB & Schema in PDF & verctor formates, etc
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      fabrication:
        description: Fabrication Outputs
        required: false
        default: true
        type: boolean

      bom:
        description: Bill of materials
        required: false
        default: true
        type: boolean

      models:
        description: 3D renderings, Step files
        required: false
        default: true
        type: boolean

      docs:
        description: PCB & Schema in PDF & verctor formates, etc
        required: false
        default: true
        type: boolean

  push:
    branches:
      - dev
      - main

    tags:
      - 'v*'
      - 'rc*'

    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yaml'
      - '.github/workflows/upload-release-assets.yaml'
      - '.github/workflows/release-drafter.yaml'
      - '.github/release-drafter.yml'
  pull_request:
    types: [opened, reopened, synchronize]


env:
  KIBOT_CFG: Skyduino-Hardware.kibot.yaml
  SCHEMA_FILE: SkyDuino-Hardware.kicad_sch
  PCB_FILE: SkyDuino-Hardware.kicad_pcb
  OUTPUT_DIR: output


jobs:
  PreFlight:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run PreFlight checks
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        targets: __NONE__
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}

    - name: Retrieve results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: preflight
        path: ${{ env.OUTPUT_DIR }}


  fabrication:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.fabrication }}
    name: "Fabrication"
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: gerbers drill position

    - name: upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Fabrication
        path: ${{ env.OUTPUT_DIR }}


  BOMs:
    name: "BOMs"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.bom }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: bom_xlsx bom_html ibom

    - name: upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: BOMs
        path: ${{ env.OUTPUT_DIR }}


  jlcpcb:
    name: "JLCPCB BOM & Placement files"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.bom || inputs.fabrication }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      name: JLCPCB BOM
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: bom_csv position
        variant: jlcpcb

    - name: upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB-Assembly
        path: ${{ env.OUTPUT_DIR }}


  models3D:
    name: 3d Renderings & step models
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.models }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: 3D 3D_top_view

    - name: Upload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: 3D
        path: ${{ env.OUTPUT_DIR }}


  Docs:
    name: PCB & Schematic printouts
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.docs }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        verbose: ${{ vars.VERBOSE_LEVEL != '' && vars.VERBOSE_LEVEL || 0 }}
        targets: >-
            print_sch print_pdf
            board_top board_top_filled
            board_bottom board_bottom_filled

    - name: Upload Docs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Doc
        path: ${{ env.OUTPUT_DIR }}


  Blender:
    name: 3d HQ Rendering
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      if: false
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        install3D: yes
        targets: 3D_top_view_HQ

    - name: Upload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: 3D-HQ
        path: ${{ env.OUTPUT_DIR }}


  Diffs:
    name: Generate PCB & Schematic diffs
    runs-on: ubuntu-latest
    env:
        DIFF_OLD: ${{ github.event_name == 'pull_request' && format('{0}/{1}', 'origin', github.base_ref) || '' }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: get_last_release_tag
      name: Get Last release tag name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        if [ -z "${{ env.DIFF_OLD }}" ]
        then
          RELEASE_TAG=$(gh release ls --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName')
          if [ -z "$RELEASE_TAG" ]
          then
            RELEASE_TAG="KIBOT_LAST-1"
          fi
        else
          RELEASE_TAG="${{ env.DIFF_OLD }}"
        fi
        echo "TAG_NAME=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
        echo "::notice::Calculated Release Tag: $RELEASE_TAG"

    - uses: INTI-CMNB/KiBot@v2_k8
      name: PCB & Schematic Diff
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        verbose: ${{ vars.VERBOSE_LEVEL != '' && vars.VERBOSE_LEVEL || 0 }}
        targets: >-
            -E DIFF_OLD='${{ steps.get_last_release_tag.outputs.TAG_NAME }}'
            pcb_diff sch_diff

    - name: Upload PCB & Schematic Diffs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Diff
        path: ${{ env.OUTPUT_DIR }}/Diff/


  UploadAssets:
    name: Upload Assets
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - fabrication
      - BOMs
      - models3D
      - Docs
      - Blender
      - jlcpcb
      - Diffs
    uses: ./.github/workflows/upload-release-assets.yaml
