name: "Variants demo using GitHub actions"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yml'
  repository_dispatch:
    types: [run_gha]

  workflow_dispatch:
    inputs:
      fabrication:
        description: Fabrication Outputs
        required: false
        default: true
        type: boolean

      bom:
        description: Bill of materials
        required: false
        default: true
        type: boolean

      everything_else:
        description: 3D model, PDF files, renderings, etc
        required: false
        default: true
        type: boolean


env:
  KIBOT_CFG: Skyduino-Hardware.kibot.yaml
  SCHEMA_FILE: SkyDuino-Hardware.kicad_sch
  PCB_FILE: SkyDuino-Hardware.kicad_pcb


jobs:
  PreFlight:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run PreFlight checks
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: Generated
        targets: __NONE__
        config: ${{ env.KIBOT_CFG }}
        schama: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: preflight
        path: Generated


  fabrication:
    name: "Fabrication"
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: default
        config: ${{ env.KIBOT_CFG }}
        schama: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: all
        targets: gerbers dril postion

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: Fabrication
        path: default


  BOMs:
    name: "BOMs"
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: default
        config: ${{ env.KIBOT_CFG }}
        schama: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: all
        targets: bom_xlsx bom_html ibom

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: BOMs
        path: default


  Docs:
    name: Everything else
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: default
        config: ${{ env.KIBOT_CFG }}
        schama: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: all
        targets: >-
            print_sch print_pdf
            board_top board_top_filled
            board_bottom board_bottom_filled
            3D 3D_top_view

    - name: Doc
      uses: actions/upload-artifact@v4
      with:
        name: Doc
        path: default