name: "Skyduino Roaster PCB"

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      fabrication:
        description: Fabrication Outputs
        required: false
        default: true
        type: boolean

      bom:
        description: Bill of materials
        required: false
        default: true
        type: boolean

      models:
        description: 3D renderings, Step files
        required: false
        default: true
        type: boolean

      docs:
        description: PCB & Schema in PDF & verctor formates, etc
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      fabrication:
        description: Fabrication Outputs
        required: false
        default: true
        type: boolean

      bom:
        description: Bill of materials
        required: false
        default: true
        type: boolean

      models:
        description: 3D renderings, Step files
        required: false
        default: true
        type: boolean

      docs:
        description: PCB & Schema in PDF & verctor formates, etc
        required: false
        default: true
        type: boolean

  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yml'
      - '.github/workflows/main.yml'
  pull_request:
    types: [opened, reopened, synchronize]


env:
  KIBOT_CFG: Skyduino-Hardware.kibot.yaml
  SCHEMA_FILE: SkyDuino-Hardware.kicad_sch
  PCB_FILE: SkyDuino-Hardware.kicad_pcb
  OUTPUT_DIR: output


jobs:
  PreFlight:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run PreFlight checks
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        targets: __NONE__
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}

    - name: Retrieve results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: preflight
        path: ${{ env.OUTPUT_DIR }}


  fabrication:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || inputs.fabrication }}
    name: "Fabrication"
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: gerbers drill position

    - name: upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Fabrication
        path: ${{ env.OUTPUT_DIR }}


  BOMs:
    name: "BOMs"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_requests' || inputs.bom }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: bom_xlsx bom_html ibom

    - name: upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: BOMs
        path: ${{ env.OUTPUT_DIR }}


  models3D:
    name: 3d Renderings & step models
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_requests' || inputs.models }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: 3D 3D_top_view

    - name: Upload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: 3D
        path: ${{ env.OUTPUT_DIR }}


  Docs:
    name: PCB & Schematic printouts
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_requests' || inputs.docs }}
    runs-on: ubuntu-latest
    needs: [PreFlight]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        targets: >-
            print_sch print_pdf
            board_top board_top_filled
            board_bottom board_bottom_filled

    - name: Upload Docs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Doc
        path: ${{ env.OUTPUT_DIR }}