name: "Draft Release notes"

# Controls when the action will run.
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read

jobs:
  update_draft_release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: event_content_debug
        name: print event content if debug is enabled
        if: ${{ vars.DEBUG == 'yes' }}
        run: echo "${{ toJSON(github.event) }}"

      # Drafts your next Release notes as Pull Requests are merged into "dev" or "master"
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}