name: "Draft Release notes"

# Controls when the action will run.
on:
  push:
    branches: [dev, master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "dev" or "master"
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}